### ISSUE TITLE
Regarding code specifications or style 

### ISSUE THREAD

**Issue by techoner** [casbin/lua-casbin#30]
I suggest that we should follow a coding style, such as : [lua-style-guide](https://github.com/luarocks/lua-style-guide).

**Comment by hsluoyz** [comment]
@techoner good idea, is there any linter tool we can utilize? Because it's hard to review PR with the coding guide just via human eyes.

**Comment by RobotHuang** [comment]
https://github.com/mpeterv/luacheck this might be useful

**Comment by hsluoyz** [comment]
@RobotHuang good, but how to integrate it into our pipeline? Like local test run, git commit hook run or GitHub Pull Request checks.

**Comment by RobotHuang** [comment]
@hsluoyz https://github.com/RobotHuang/lua-action/blob/master/.github/workflows/main.yml#L37 this is a simple example. We also could use other's action, like https://github.com/marketplace/actions/luacheck

**Comment by hsluoyz** [comment]
@RobotHuang good! Let's integrate it into this repo.

**Comment by hsluoyz** [comment]
@rushitote any thoughts on this?

**Comment by rushitote** [comment]
@hsluoyz 
I believe the two major styles we don't follow are:

- Indentation: We use the standard 4-spaced indentation while LuaRocks recommends 3-spaces.
- Casing: Since this project has followed jCasbin and Casbin (Go), it followed the camelCase while LuaRocks recommends snake_case. 

Should we refactor it to follow LuaRocks or we follow our current style?

**Comment by hsluoyz** [comment]
There's no hard requirement for Lua coding styles. For easier porting code from Go/Java to Lua, I think currently 4 spaces and camelCase sound OK for now.
